language: node_js
node_js:
- '4.2'
env:
- CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
notifications:
  slack:
    secure: Xv587tVoehDCzyfKol9T8qF50SGzqkz6vFAwBnGQAcBFxa4JsiIN2at4igKtIco3B$



